version: '3'

services:
  app:
    depends_on:
      - db
    build: ./api
    ports:
      - 3000:3000
    volumes:
      - ./api:/home/node/app
  
  db:
    image: gestaoobra-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: MainUser
      MYSQL_PASSWORD: MainPassword